name: Coverage

on:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    if: github.repository_owner == 'ruka-lang'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - name: Install kcov
        run: sudo apt install -y kcov

      - name: Generate Coverage
        run: zig build coverage --summary all

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: zig-out/coverage/kcov-merged
          fail_ci_if_error: true
          verbose: true
